### ISSUE TITLE
Ekran logowania

### ISSUE THREAD

**Issue by Iartur221** [HakierGrzonzo/Kronikarz#29]
**Założenia:**
-Obsługa sytuacji błędnego loginu/hasła
-Przycisk "Zaloguj" pojawi się dopiero po uzupełnieniu obu pól
-Ograniczenie liczby znaków loginu i hasła tak, by nie wyszły poza wyznaczone pola
-Po kliknięciu w logo cofnie nas do ekranu głównego
-Po nieaktywności dłuższej niż 20sekund cofnie nas do ekranu głównego

**Comment by Iartur221** [comment]
![Image](https://user-images.githubusercontent.com/72377504/197890990-38af1604-127d-4b93-9c6c-6790c3133be4.png)

**Comment by Havystar** [comment]
Dostane może tą czcionkę? Oraz czy jesteś pewny czy takie okrągłe inputy będą user friendly oraz czy używając  https://suid.io/components/text-field oraz css to tak fajnie wyjdzie? Co do przycisku i reszty to approve <3

**Comment by Iartur221** [comment]
> 

https://www.dafontfree.co/ink-free-font/ tu czcionka. Co do inputów nie ma problemu, można zrobić prostokątne ale wycentrowane w takim obszarze, tak jak mamy "Zaloguj", no i button na wyznaczonym obszarze tym okrągłym będzie nam odpalał to pole tekstowe

**Comment by Havystar** [comment]
a jakiś efect hover albo po kliknienciu na przycisk?

**Comment by Iartur221** [comment]
Myślę, że takie upiększenia to jak już będzie nam stała apka, a na razie nie ma co zmieniać z domyślnych. Tak samo jakieś przejścia, animacje itd
