### ISSUE TITLE
[SPIKE] Jak narysować w przeglądarce drzewo z relacjami

### ISSUE THREAD

**Issue by HakierGrzonzo** [HakierGrzonzo/Kronikarz#3]
Należy znaleźć najlepszy sposób na rysowanie drzew z różnymi relacjami w przeglądarce.

Możliwe podejścia:
- HTML w SVG w HTML
- Canvas

**Comment by Havystar** [comment]
Wykorzystamy na razie bibliotekę vis która wspiera strukturę grafową i będziemy ją w odpowiedni sposób customizować oraz dopisać całą logikę edycji oraz zrobić customowy contex menu który będzie musiał być z nią połączony
