### ISSUE TITLE
Ekran Startowy

### ISSUE THREAD

**Issue by Iartur221** [HakierGrzonzo/Kronikarz#37]
**Założenia:**
-Po kliknięciu przycisku "Logowanie" przenosi nas do ekranu logowania #29 
-Po kliknięciu przycisku "Rejestracja" przenosi nas do ekranu rejestracji #31

**Comment by Iartur221** [comment]
![Image](https://user-images.githubusercontent.com/72377504/197892403-b0328d5c-5b01-45b9-8ab4-9310c3ef7038.png)

**Comment by Havystar** [comment]
Aproved, jest jakiś hover po najechaniu na te przyciski?
